// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RoomsEnglish.Infraestructure.Data.Context;

#nullable disable

namespace RoomsEnglish.Infraestructure.Data.Migrations
{
    [DbContext(typeof(ApplicationDataContext))]
    [Migration("20240206032356_PlayerContext")]
    partial class PlayerContext
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RoomsEnglish.Domain.PlayerContext.Entities.Player", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar")
                        .HasColumnName("USER_EMAIL");

                    b.Property<int>("Experience")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(5)
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("PLAYER_EXPERIENCE");

                    b.Property<int>("Level")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(5)
                        .HasColumnType("int")
                        .HasDefaultValue(1)
                        .HasColumnName("PLAYER_LEVEL");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar")
                        .HasColumnName("PLAYER_NAME");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("varchar")
                        .HasColumnName("USER_PASSWORD");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "Email" }, "IX_PLAYERS_EMAIL")
                        .IsUnique();

                    b.ToTable("PLAYERS", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
